app:
  name: Ping

quarkus:
  http:
    port: 20080
  grpc:
    server:
      port: 29000
  rest-client:
    PongServiceApiProxy:
      url: http://localhost:30080/
    RabbitMqApiProxy:
      url: http://localhost:15672/

camel:
  rabbit-mq:
    exchange: ping-exchange
    hostname: localhost
    port: 5672
    username: guest
    password: guest
    queue: ping-queue

health:
  ping-service-health-url: http://localhost:20080/q/health
